In [1]:
# Introduction to Pandas
import pandas as pd

1. What is Pandas?
Pandas is an open-source Python library used for working with structured or tabular data. It provides powerful data structures like Series and DataFrame to efficiently store, manipulate, analyze, and visualize data.

Pandas simplifies tasks such as:

Reading data from files
Cleaning missing values
Filtering data
Sorting data
Grouping data
Performing statistical analysis
Pandas is built on top of the NumPy library, making it fast and efficient.

Example
Imagine a school has a spreadsheet containing information about 1,000 students.

Instead of manually calculating averages or finding the highest mark, Pandas can perform these operations in just a few lines of code.

In [10]:
import pandas as pd
data = {
    "Name": ["Arun", "Thamarai", "Kumar"],
    "Age": [25, 28, 30],
    "Salary": [25000, 35000, 40000]
}
df = pd.DataFrame(data)
print(df)

       Name  Age  Salary
0      Arun   25   25000
1  Thamarai   28   35000
2     Kumar   30   40000

Why Pandas?
| Task | Pandas Functionality |
|---|---|
| Read data | Load CSV, Excel, and other supported formats |
| Clean data | Handle missing and duplicate values |
| Filter data | Select rows based on conditions |
| Analyze data | Calculate mean, median, sum, and statistics |
| Transform data | Create, modify, and delete columns |
| Combine data | Merge, join, and concatenate datasets |
| Save data | Export results to CSV or Excel |
| Prepare ML data | Clean and transform features before training |

### Series
A Series is a one-dimensional labeled array that can store values such as integers, strings, floats, and other Python objects.
Think of a Series as a single column of data with an index.

In [14]:
import pandas as pd
ages = pd.Series([22, 25, 28, 30])
print(ages)

0    22
1    25
2    28
3    30
dtype: int64

In [16]:
marks = pd.Series(
    [85, 90, 78],
    index=["Arun", "Priya", "Kumar"]
)

print(marks)
print(marks["Priya"])

Arun     85
Priya    90
Kumar    78
dtype: int64
90

Important Series attributes and methods
Attribute / Method	Purpose
s.index	- Returns index labels
s.values - Returns underlying values
s.dtype	- Returns data type
s.shape	- Returns the number of elements as a tuple
s.size	- Returns the total number of elements
s.head() - Displays the first five values by default
s.tail() - Displays the last five values by default
s.mean() - Calculates the average
s.sum() - Calculates the total

### DataFrame
A DataFrame is a two-dimensional labeled data structure consisting of rows and columns.
Think of a DataFrame as an Excel sheet or SQL table.

In [21]:
import pandas as pd
data = {
    "Name": ["Arun", "Priya", "Kumar"],
    "Age": [22, 25, 28],
    "Marks": [85, 90, 78]
}
df = pd.DataFrame(data)
print(df)

    Name  Age  Marks
0   Arun   22     85
1  Priya   25     90
2  Kumar   28     78

In [23]:
print(df.shape)
print(df.size)
print(df.ndim)
print(df.index)
print(df.columns)
print(df.dtypes)

(3, 3)
9
2
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'Marks'], dtype='object')
Name     object
Age       int64
Marks     int64
dtype: object

### Creating DataFrames
There are several ways to create a DataFrame.
Method 1: From a dictionary

In [26]:
import pandas as pd
data = {
    "Name": ["Arun", "Priya"],
    "Age": [22, 25]
}
df = pd.DataFrame(data)
print(df)

    Name  Age
0   Arun   22
1  Priya   25

In [28]:
# Method 2: From a list of lists
data = [
    ["Arun", 22],
    ["Priya", 25],
    ["Kumar", 28]
]

df = pd.DataFrame(data, columns=["Name", "Age"])
print(df)

    Name  Age
0   Arun   22
1  Priya   25
2  Kumar   28

In [30]:
#Method 3: From a list of dictionaries
data = [
    {"Name": "Arun", "Age": 22},
    {"Name": "Priya", "Age": 25},
    {"Name": "Kumar", "Age": 28}
]

df = pd.DataFrame(data)
print(df)

    Name  Age
0   Arun   22
1  Priya   25
2  Kumar   28

### 6. Data Types
Each DataFrame column has a specific data type that determines what kind of values it can store.

Common data types include:

* int64
* float64
* object (strings)
* bool
* datetime64

In [35]:
import pandas as pd

df = pd.DataFrame({
    "Age":[22,23],
    "Name":["Thamarai","Rahul"],
    "Passed":[True,False]
})

print(df.dtypes)

Age        int64
Name      object
Passed      bool
dtype: object

Important: int64 cannot represent a missing integer value directly, while Pandas' nullable Int64 type can represent missing values using pd.NA.

### 7. Index
An index identifies rows in a Series or DataFrame. By default, Pandas assigns integer labels starting at 0.
Default index

In [41]:
df = pd.DataFrame({
    "Name": ["Arun", "Priya", "Kumar"],
    "Age": [22, 25, 28]
})

print(df.index)

RangeIndex(start=0, stop=3, step=1)

df.index = ["A", "B", "C"]

print(df)

In [45]:
df = df.reset_index()
print(df)

  index   Name  Age
0     A   Arun   22
1     B  Priya   25
2     C  Kumar   28

In [49]:
df = df.reset_index(drop=True)
print(df)

  index   Name  Age
0     A   Arun   22
1     B  Priya   25
2     C  Kumar   28

### Columns
Columns represent individual variables or features in a DataFrame.
For example, Name, Age, and Salary are columns in an employee dataset.
Selecting one column

In [52]:
print(df["Name"])

0     Arun
1    Priya
2    Kumar
Name: Name, dtype: object

Example
In an employee database:

* Employee Name
* Salary
* Department
* Experience
Each is stored as a separate column.

### AI/ML Usage
Each column generally represents one feature used for prediction.

In [61]:
df["Age"] = df["Age"] + 1
df

  index   Name  Age
0     A   Arun   25
1     B  Priya   28
2     C  Kumar   31

In [63]:
df = df.rename(columns={"Name": "Employee_Name"})
df

  index Employee_Name  Age
0     A          Arun   25
1     B         Priya   28
2     C         Kumar   31

In [65]:
df = df.drop(columns=["index"])
df

  Employee_Name  Age
0          Arun   25
1         Priya   28
2         Kumar   31

### Reading Data
Reading data means importing data from external files into a Pandas DataFrame so that it can be analyzed and processed.

Pandas supports many file formats such as:

* CSV
* Excel
* JSON
* SQL Database
* Parquet

In [68]:
import pandas as pd
students = pd.DataFrame({
    "ID": [101, 102, 103, 104],
    "Name": ["Aishu", "Rahul", "Priya", "John"],
    "Age": [22, 23, 21, 24],
    "Marks": [95, 88, 91, 84]
})

print(students)

    ID   Name  Age  Marks
0  101  Aishu   22     95
1  102  Rahul   23     88
2  103  Priya   21     91
3  104   John   24     84

In [70]:
### Create a CSV File
students.to_csv("students.csv", index=False)
print("CSV file created successfully.")

CSV file created successfully.

In [72]:
#Read CSV File
df = pd.read_csv("students.csv")
print(df)

    ID   Name  Age  Marks
0  101  Aishu   22     95
1  102  Rahul   23     88
2  103  Priya   21     91
3  104   John   24     84

In [74]:
#Create an Excel File
students.to_excel("students.xlsx", index=False)
print("Excel file created successfully.")

Excel file created successfully.

In [76]:
#Read Excel File
df = pd.read_excel("students.xlsx")
print(df)

    ID   Name  Age  Marks
0  101  Aishu   22     95
1  102  Rahul   23     88
2  103  Priya   21     91
3  104   John   24     84

In [78]:
#Create a JSON File
students.to_json("students.json", orient="records", indent=4)
print("JSON file created successfully.")

JSON file created successfully.

In [80]:
#Read JSON File
df = pd.read_json("students.json")
print(df)

    ID   Name  Age  Marks
0  101  Aishu   22     95
1  102  Rahul   23     88
2  103  Priya   21     91
3  104   John   24     84

Parameter	Purpose
filepath	File path
usecols	Read selected columns
nrows	Read a limited number of rows
skiprows	Skip specified rows
index_col	Use a column as the index
dtype	Specify column data types
na_values	Define additional missing-value markers
encoding	Specify text encoding
parse_dates	Parse selected columns as dates where supported

### AI/ML Usage
Datasets downloaded from Kaggle or company databases are usually stored as CSV or Excel files. Pandas loads these datasets before preprocessing and training machine learning models.

### Writing Data
Writing data means saving a DataFrame into a file so it can be shared, stored, or used later.

Pandas supports writing to:

* CSV
* Excel
* JSON
8 Create a New DataFrame

In [86]:
import pandas as pd
employees = pd.DataFrame({
    "Employee_ID": [1, 2, 3],
    "Name": ["John", "Sara", "David"],
    "Department": ["IT", "HR", "Finance"],
    "Salary": [50000, 45000, 60000]
})

print(employees)

   Employee_ID   Name Department  Salary
0            1   John         IT   50000
1            2   Sara         HR   45000
2            3  David    Finance   60000

In [88]:
#Write to CSV
employees.to_csv("employees.csv", index=False)
print("employees.csv saved successfully.")

employees.csv saved successfully.

In [90]:
#Write to Excel
employees.to_excel("employees.xlsx", index=False)
print("employees.xlsx saved successfully.")

employees.xlsx saved successfully.

In [92]:
#Write to JSON
employees.to_json("employees.json", orient="records", indent=4)
print("employees.json saved successfully.")

employees.json saved successfully.

In [96]:
#Verify the Saved Files
csv_data = pd.read_csv("employees.csv")
excel_data = pd.read_excel("employees.xlsx")
json_data = pd.read_json("employees.json")
print(csv_data)

print(excel_data)

print(json_data)

   Employee_ID   Name Department  Salary
0            1   John         IT   50000
1            2   Sara         HR   45000
2            3  David    Finance   60000
   Employee_ID   Name Department  Salary
0            1   John         IT   50000
1            2   Sara         HR   45000
2            3  David    Finance   60000
   Employee_ID   Name Department  Salary
0            1   John         IT   50000
1            2   Sara         HR   45000
2            3  David    Finance   60000

Writing functions comparison
Function	Purpose
df.to_csv()	Save as CSV
df.to_excel()	Save as Excel
df.to_json()	Save as JSON
df.to_parquet()	Save as Parquet
df.to_sql()	Write to a SQL table

In [98]:
import pandas as pd

data = {
    "Name": ["Arun", "Priya", "Kumar", "Divya"],
    "Age": [22, 25, 28, 24],
    "Salary": [25000, 35000, 40000, 30000],
    "Department": ["IT", "HR", "IT", "Finance"]
}

df = pd.DataFrame(data)

# 1. Display the first two rows
print(df.head(2))

# 2. Display the shape
print(df.shape)

# 3. Display only the Name column
print(df["Name"])

# 4. Display Name and Salary
print(df[["Name", "Salary"]])

# 5. Display employees whose salary is greater than 30000
print(df[df["Salary"] > 30000])

# 6. Calculate the average salary
print(df["Salary"].mean())

# 7. Save the dataset
df.to_csv("employees.csv", index=False)

    Name  Age  Salary Department
0   Arun   22   25000         IT
1  Priya   25   35000         HR
(4, 4)
0     Arun
1    Priya
2    Kumar
3    Divya
Name: Name, dtype: object
    Name  Salary
0   Arun   25000
1  Priya   35000
2  Kumar   40000
3  Divya   30000
    Name  Age  Salary Department
1  Priya   25   35000         HR
2  Kumar   28   40000         IT
32500.0