In [1]:
#Data_Manipulation
import pandas as pd

In [2]:
#Create a Sample Dataset
students = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104, 105, 105],
    "Name": ["Thamarai", "Rahul", "Selvan", "John", "Mohan", "Meena"],
    "Age": [22, 23, 21, 24, 22, 22],
    "Department": ["AI", "ML", "DS", "AI", "ML", "ML"],
    "Marks": [95, 88, 91, 84, 89, 89]
})

print(students)

   Student_ID      Name  Age Department  Marks
0         101  Thamarai   22         AI     95
1         102     Rahul   23         ML     88
2         103    Selvan   21         DS     91
3         104      John   24         AI     84
4         105     Mohan   22         ML     89
5         105     Meena   22         ML     89

### 1. Rename Columns
Renaming columns changes one or more column names in a DataFrame to make them more meaningful or consistent.

Syntax:

df.rename(columns={"old_name":"new_name"})

#### Example:

A company changes the column name Emp_ID to Employee_ID to improve readability.

#### AI/ML Usage
Meaningful column names make datasets easier to understand and document.

In [4]:
students.rename(columns={"Marks":"Score"})

   Student_ID      Name  Age Department  Score
0         101  Thamarai   22         AI     95
1         102     Rahul   23         ML     88
2         103    Selvan   21         DS     91
3         104      John   24         AI     84
4         105     Mohan   22         ML     89
5         105     Meena   22         ML     89

### 2. Drop Rows
drop() removes one or more rows from a DataFrame.

Syntax:

df.drop(index)

#### Example:

An HR analyst removes employees who have resigned from the dataset.

#### AI/ML Usage
Used to remove incorrect or unnecessary records before model training.

Remove row index 3.

In [6]:
students.drop(3)

   Student_ID      Name  Age Department  Marks
0         101  Thamarai   22         AI     95
1         102     Rahul   23         ML     88
2         103    Selvan   21         DS     91
4         105     Mohan   22         ML     89
5         105     Meena   22         ML     89

In [7]:
students.drop([1,4])

   Student_ID      Name  Age Department  Marks
0         101  Thamarai   22         AI     95
2         103    Selvan   21         DS     91
3         104      John   24         AI     84
5         105     Meena   22         ML     89

### 3. Drop Columns
Columns that are unnecessary can be removed using drop().

Syntax:

df.drop(columns=["Column_Name"])

#### Example:

A hospital removes the Patient_Address column before sharing data for research.

#### AI/ML Usage
Removes irrelevant features that do not contribute to model performance.

In [9]:
students.drop(columns=["Age"])

   Student_ID      Name Department  Marks
0         101  Thamarai         AI     95
1         102     Rahul         ML     88
2         103    Selvan         DS     91
3         104      John         AI     84
4         105     Mohan         ML     89
5         105     Meena         ML     89

### 4. Insert Columns
insert() adds a new column at a specific position.

Syntax:

df.insert(location, column_name, values)

#### Example:

A school adds a Grade column after calculating marks.

#### AI/ML Usage
New features are often inserted after feature engineering.

In [11]:
students.insert(5, "Grade", ["A", "B", "A", "C", "B", "B"])
print(students)

   Student_ID      Name  Age Department  Marks Grade
0         101  Thamarai   22         AI     95     A
1         102     Rahul   23         ML     88     B
2         103    Selvan   21         DS     91     A
3         104      John   24         AI     84     C
4         105     Mohan   22         ML     89     B
5         105     Meena   22         ML     89     B

### 5. assign()
assign() creates new columns without modifying the original DataFrame.

Syntax:
df.assign(NewColumn=values)

#### Example
A company creates a new column showing whether an employee is eligible for a bonus.

#### AI/ML Usage
Used for feature engineering while preserving the original dataset.

In [13]:
students_new = students.assign(
    Pass=students["Marks"] >= 90
)

print(students_new)

   Student_ID      Name  Age Department  Marks Grade   Pass
0         101  Thamarai   22         AI     95     A   True
1         102     Rahul   23         ML     88     B  False
2         103    Selvan   21         DS     91     A   True
3         104      John   24         AI     84     C  False
4         105     Mohan   22         ML     89     B  False
5         105     Meena   22         ML     89     B  False

### 6. apply()
apply() applies a function to rows or columns.

Syntax:

df["Column"].apply(function)

#### Example:

A teacher adds grace marks to every student's score.

#### AI/ML Usage
Used for feature transformation and preprocessing.

In [23]:
students["Name"].apply(str.upper)

0    THAMARAI
1       RAHUL
2      SELVAN
3        JOHN
4       MOHAN
5       MEENA
Name: Name, dtype: object

### 7. map()
map() replaces or transforms values in a single column.

Syntax:

df["Column"].map(dictionary)

#### Example:

Convert department codes into department names.

#### AI/ML Usage
Used to encode or decode categorical values.

In [26]:
grade_map = {
    "A": "Excellent",
    "B": "Good",
    "C": "Average"
}

students["Performance"] = students["Grade"].map(grade_map)

print(students)

   Student_ID      Name  Age Department  Marks Grade Performance
0         101  Thamarai   22         AI     95     A   Excellent
1         102     Rahul   23         ML     88     B        Good
2         103    Selvan   21         DS     91     A   Excellent
3         104      John   24         AI     84     C     Average
4         105     Mohan   22         ML     89     B        Good
5         105     Meena   22         ML     89     B        Good

### 8. replace()
replace() substitutes one value with another.

Syntax:

df.replace(old, new)

#### Example:

A company changes department abbreviations into full names.

#### AI/ML Usage
Used to standardize inconsistent values before model training.

In [29]:
students=students.replace({
    "Department":{
        "AI":"Artificial Intelligence",
        "ML":"Machine Learning",
        "DS":"Data Science"
    }
})

print(students)

   Student_ID      Name  Age               Department  Marks Grade Performance
0         101  Thamarai   22  Artificial Intelligence     95     A   Excellent
1         102     Rahul   23         Machine Learning     88     B        Good
2         103    Selvan   21             Data Science     91     A   Excellent
3         104      John   24  Artificial Intelligence     84     C     Average
4         105     Mohan   22         Machine Learning     89     B        Good
5         105     Meena   22         Machine Learning     89     B        Good

### 9. Duplicate Handling
Duplicate handling identifies and removes repeated rows from a dataset.

Why is it Important?
Duplicate data can produce incorrect analysis and reduce machine learning model accuracy.

#### Example:

An online shopping website accidentally stores the same customer order twice. Duplicate records are removed before generating sales reports.

#### AI/ML Usage
Duplicate records can bias machine learning models. Removing duplicates improves data quality and model performance.