### Grouping & Aggregation

In [2]:
import pandas as pd
students = pd.DataFrame({
    "Student_ID": [101,102,103,104,105,106,107,108],
    "Name": ["Thamarai","Rahul","Kaviya","John","Meera","David","Sneha","Arun"],
    "Department": ["AI","ML","AI","DS","ML","DS","AI","ML"],
    "Gender": ["Male","Male","Female","Male","Female","Male","Female","Male"],
    "Marks": [95,88,91,84,89,76,98,92],
    "Age": [22,23,21,24,22,23,21,22]
})

print(students)

   Student_ID      Name Department  Gender  Marks  Age
0         101  Thamarai         AI    Male     95   22
1         102     Rahul         ML    Male     88   23
2         103    Kaviya         AI  Female     91   21
3         104      John         DS    Male     84   24
4         105     Meera         ML  Female     89   22
5         106     David         DS    Male     76   23
6         107     Sneha         AI  Female     98   21
7         108      Arun         ML    Male     92   22

### 1. groupby()
groupby() divides data into groups based on one or more columns and performs operations on each group independently.

It is similar to SQL's GROUP BY clause.

Syntax:

df.groupby("column")

Example:

A company calculates the average salary for each department.

#### AI/ML Usage
Used to summarize data before feature engineering and exploratory data analysis (EDA).

In [4]:
students.groupby("Department")["Marks"].mean()

Department
AI    94.666667
DS    80.000000
ML    89.666667
Name: Marks, dtype: float64

In [5]:
# Group by Multiple Columns
students.groupby(["Department","Gender"])["Marks"].mean()

Department  Gender
AI          Female    94.5
            Male      95.0
DS          Male      80.0
ML          Female    89.0
            Male      90.0
Name: Marks, dtype: float64

### 2. agg()
agg() (Aggregate) performs multiple calculations on grouped data simultaneously.

Syntax:

df.groupby("column").agg(functions)

Example:

A bank calculates:

* Average balance
* Maximum balance
* Number of customers
for each branch.

#### AI/ML Usage
Used to generate statistical summaries of grouped features.

In [7]:
students.groupby("Department")["Marks"].agg(
    ["mean","max","min","count"]
)

                 mean  max  min  count
Department
AI          94.666667   98   91      3
DS          80.000000   84   76      2
ML          89.666667   92   88      3

In [8]:
# Multiple Columns
students.groupby("Department").agg({
    "Marks":["mean","max"],
    "Age":"mean"
})

                Marks            Age
                 mean max       mean
Department
AI          94.666667  98  21.333333
DS          80.000000  84  23.500000
ML          89.666667  92  22.333333

### 3. transform()
Definition

transform() performs calculations on each group but returns a result with the same number of rows as the original DataFrame.

#### Example:

Each employee's salary is compared with the average salary of their department.

#### AI/ML Usage
Used for feature engineering by creating normalized or group-based features.

In [10]:
students["Department_Average"] = students.groupby(
    "Department"
)["Marks"].transform("mean")

print(students)

   Student_ID      Name Department  Gender  Marks  Age  Department_Average
0         101  Thamarai         AI    Male     95   22           94.666667
1         102     Rahul         ML    Male     88   23           89.666667
2         103    Kaviya         AI  Female     91   21           94.666667
3         104      John         DS    Male     84   24           80.000000
4         105     Meera         ML  Female     89   22           89.666667
5         106     David         DS    Male     76   23           80.000000
6         107     Sneha         AI  Female     98   21           94.666667
7         108      Arun         ML    Male     92   22           89.666667

### 4. filter()
filter() removes groups that do not satisfy a specified condition.

#### Example:

A company keeps only departments whose average sales exceed ₹1,00,000.

#### AI/ML Usage
Useful for removing weak or insignificant groups before analysis.

In [12]:
students.groupby("Department").filter(
    lambda x: x["Marks"].mean() > 90
)

   Student_ID      Name Department  Gender  Marks  Age  Department_Average
0         101  Thamarai         AI    Male     95   22           94.666667
2         103    Kaviya         AI  Female     91   21           94.666667
6         107     Sneha         AI  Female     98   21           94.666667

### 5. Pivot Tables
A Pivot Table summarizes data by grouping rows and columns while applying aggregation functions.

It provides a spreadsheet-like summary.

Syntax:

pd.pivot_table()

Example:

A company creates a report showing average monthly sales for each branch.

### AI/ML Usage
Pivot tables are useful for quickly summarizing datasets during EDA.

In [14]:
pd.pivot_table(
    students,
    values="Marks",
    index="Department",
    aggfunc="mean"
)

                Marks
Department
AI          94.666667
DS          80.000000
ML          89.666667

In [15]:
# Multiple Aggregations
pd.pivot_table(
    students,
    values="Marks",
    index="Department",
    aggfunc=["mean","max","min"]
)

                 mean   max   min
                Marks Marks Marks
Department
AI          94.666667    98    91
DS          80.000000    84    76
ML          89.666667    92    88

In [16]:
# Pivot with Rows and Columns
pd.pivot_table(
    students,
    values="Marks",
    index="Department",
    columns="Gender",
    aggfunc="mean"
)

Gender      Female  Male
Department
AI            94.5  95.0
DS             NaN  80.0
ML            89.0  90.0

### 6. Crosstab
pd.crosstab() creates a frequency table showing how often combinations of categorical values occur.

Syntax:

pd.crosstab(row,column)

### Example:

A hospital counts male and female patients in each department.

### AI/ML Usage
Used to study relationships between categorical variables before model building.

In [18]:
pd.crosstab(
    students["Department"],
    students["Gender"]
)

Gender      Female  Male
Department
AI               2     1
DS               0     2
ML               1     2

In [30]:
# Crosstab with Totals
pd.crosstab(
    students["Department"],
    students["Gender"],
    margins=True
)

Gender      Female  Male  All
Department
AI               2     1    3
DS               0     2    2
ML               1     2    3
All              3     5    8

In [32]:
# Crosstab with Percentages
pd.crosstab(
    students["Department"],
    students["Gender"],
    normalize=True
)

Gender      Female   Male
Department
AI           0.250  0.125
DS           0.000  0.250
ML           0.125  0.250