### Combining Datasets

In [2]:
import pandas as pd
#Create Sample Dataset 1
students = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104],
    "Name": ["Thamarai", "Rahul", "Priya", "John"],
    "Department": ["AI", "ML", "DS", "AI"]
})

print(students)

   Student_ID      Name Department
0         101  Thamarai         AI
1         102     Rahul         ML
2         103     Priya         DS
3         104      John         AI

In [3]:
#Create Sample Dataset 2
marks = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104],
    "Marks": [95, 88, 91, 84]
})

print(marks)

   Student_ID  Marks
0         101     95
1         102     88
2         103     91
3         104     84

In [4]:
#Create Sample Dataset 3
new_students = pd.DataFrame({
    "Student_ID": [105, 106],
    "Name": ["Meena", "David"],
    "Department": ["ML", "DS"]
})

print(new_students)

   Student_ID   Name Department
0         105  Meena         ML
1         106  David         DS

### 1. concat()
concat() combines two or more DataFrames along rows or columns.

It is useful when datasets have a similar structure.

Syntax:

pd.concat([df1, df2])

#### Example:

Suppose a college stores student information in separate files:

* students_january.csv
* students_february.csv
* students_march.csv
We can combine all three datasets into one DataFrame.

In [6]:
combined_students = pd.concat(
    [students, new_students],
    ignore_index=True
)

print(combined_students)

   Student_ID      Name Department
0         101  Thamarai         AI
1         102     Rahul         ML
2         103     Priya         DS
3         104      John         AI
4         105     Meena         ML
5         106     David         DS

In [7]:
#Concatenating Columns
student_info = pd.DataFrame({
    "Name": ["Aravind", "Rahul", "Priya"],
    "Age": [22, 23, 21]
})

student_scores = pd.DataFrame({
    "Marks": [95, 88, 91],
    "Grade": ["A", "B", "A"]
})

result = pd.concat(
    [student_info, student_scores],
    axis=1
)

print(result)

      Name  Age  Marks Grade
0  Aravind   22     95     A
1    Rahul   23     88     B
2    Priya   21     91     A

### AI/ML Usage
concat() is useful when combining:

* Monthly datasets
* Yearly datasets
* Training datasets
Data collected from multiple sources

### 2. merge()
merge() combines DataFrames using one or more common columns, similar to SQL JOIN operations.

Syntax:

pd.merge(df1, df2, on="column")

Example:

Suppose a college stores, Student information and marks separately:

* Student_ID | Name | Department
* Student_ID | Marks
We can combine them using Student_ID.

In [9]:
merged_data = pd.merge(
    students,
    marks,
    on="Student_ID"
)

print(merged_data)

   Student_ID      Name Department  Marks
0         101  Thamarai         AI     95
1         102     Rahul         ML     88
2         103     Priya         DS     91
3         104      John         AI     84

### Types of Merge
Pandas supports:

* Inner Join
* Left Join
* Right Join
* Outer Join
### Inner Join
Returns only matching records.

In [11]:
pd.merge(
    students,
    marks,
    on="Student_ID",
    how="inner"
)

   Student_ID      Name Department  Marks
0         101  Thamarai         AI     95
1         102     Rahul         ML     88
2         103     Priya         DS     91
3         104      John         AI     84

### Left Join
Keeps all rows from the left DataFrame.

In [13]:
pd.merge(
    students,
    marks,
    on="Student_ID",
    how="left"
)

   Student_ID      Name Department  Marks
0         101  Thamarai         AI     95
1         102     Rahul         ML     88
2         103     Priya         DS     91
3         104      John         AI     84

### Right Join
Keeps all rows from the right DataFrame.

In [15]:
pd.merge(
    students,
    marks,
    on="Student_ID",
    how="right"
)

   Student_ID      Name Department  Marks
0         101  Thamarai         AI     95
1         102     Rahul         ML     88
2         103     Priya         DS     91
3         104      John         AI     84

### Outer Join
Keeps all rows from both DataFrames.

In [26]:
pd.merge(
    students,
    marks,
    on="Student_ID",
    how="outer"
)

   Student_ID      Name Department  Marks
0         101  Thamarai         AI     95
1         102     Rahul         ML     88
2         103     Priya         DS     91
3         104      John         AI     84

### AI/ML Usage
merge() is extremely important when combining features from different datasets.

### 3. join()
join() combines DataFrames using their index by default.

It is particularly useful when the DataFrames have matching indexes.

#### Example:
A company may have, Employee information and Employee performance :
If Employee_ID is already used as the index, join() can combine the datasets easily.

In [30]:
student_info = pd.DataFrame({
    "Name": ["Aishu", "Rahul", "Priya"],
    "Department": ["AI", "ML", "DS"]
}, index=[101, 102, 103])

student_marks = pd.DataFrame({
    "Marks": [95, 88, 91]
}, index=[101, 102, 103])

In [32]:
result = student_info.join(student_marks)
print(result)

      Name Department  Marks
101  Aishu         AI     95
102  Rahul         ML     88
103  Priya         DS     91

In [34]:
#Types of Joins
# Left Join
student_info.join(
    student_marks,
    how="left"
)

      Name Department  Marks
101  Aishu         AI     95
102  Rahul         ML     88
103  Priya         DS     91

In [36]:
# Inner Join
student_info.join(
    student_marks,
    how="inner"
)

      Name Department  Marks
101  Aishu         AI     95
102  Rahul         ML     88
103  Priya         DS     91

### AI/ML Usage
join() can be useful when feature datasets are indexed using a common identifier.

### 4. append() — Deprecation and Alternative
append() was previously used to add rows from one DataFrame to another.

Older Pandas Code:

df1.append(df2)

However, DataFrame.append() was deprecated in Pandas 1.4 and removed in Pandas 2.0.

Therefore, we should not use append() in modern Pandas.

#### Old Code:

result = students.append(new_students)

--> Old approach - do not use in modern Pandas

This may produce:

AttributeError: 'DataFrame' object has no attribute 'append'

Why was append() removed?

concat() is more flexible and efficient for combining multiple DataFrames.

Instead of:

df1.append(df2)

use:

pd.concat([df1, df2])

In [39]:
# Modern Alternative: concat()
result = pd.concat(
    [students, new_students],
    ignore_index=True
)

print(result)

   Student_ID      Name Department
0         101  Thamarai         AI
1         102     Rahul         ML
2         103     Priya         DS
3         104      John         AI
4         105     Meena         ML
5         106     David         DS

#### AI/ML Usage:
When new batches of training data arrive, use concat() to combine them with existing data.

### 5. combine_first()
combine_first() fills missing values in one DataFrame using values from another DataFrame.

It is particularly useful when two datasets contain partial information.

In [42]:
# Create Sample Data
student_data1 = pd.DataFrame({
    "Name": ["Aishu", "Rahul", "Priya"],
    "Marks": [95, None, 91]
})

student_data2 = pd.DataFrame({
    "Name": ["Aishu", "Rahul", "Priya"],
    "Marks": [None, 88, 92]
})

In [44]:
result = student_data1.combine_first(student_data2)

print(result)

    Name  Marks
0  Aishu   95.0
1  Rahul   88.0
2  Priya   91.0